biisis/urls.py
from django.conf.urls import patterns, url

from biisis import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<biisi_id>\d+)/$', views.detail, name='detail'),
    url(r'create_biisi/', views.create_biisi, name="create_biisi"),
    url(r'^(?P<biisi_id>\d+)/change_laji/$', views.change_laji, name='change_laji'),
)

termostaatti/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'termostaatti.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^biisis/', include('biisis.urls', namespace="biisis")),
    url(r'^admin/', include(admin.site.urls)),
)

biisis/models.py
from django.db import models

# Create your models here.

class Biisi(models.Model):
    nimi = models.CharField(max_length=200)
    esittaja = models.CharField(max_length=200) 
    soinnut = models.CharField(max_length=200)
    linkki = models.CharField(max_length=200)

biisis/views.py
from biisis.models import Biisi
from django.http import Http404

from django.http import HttpResponse
from django.shortcuts import render,  redirect, get_object_or_404
from django.template import RequestContext, loader

def index(request):
    biisis = Biisi.objects.all()
    context = {'biisis': biisis}
    return render(request, 'biisis/index.html', context)

def detail(request, biisi_id):
    try:
        biisi = Biisi.objects.get(pk=biisi_id)
        splittaus = biisi.soinnut.split(', ')
    except Biisi.DoesNotExist:
        raise Http404
    return render(request, 'biisis/detail.html', {'biisi': biisi, 'splittaus': splittaus})

def create_biisi(request):
    new = Biisi(nimi="default nimi", esittaja="default esittaja", soinnut="default soinnut")
    esittaja = request.GET['esittaja']
    nimi = request.GET['nimi']
    soinnut = request.GET['soinnut']
    linkki = request.GET['linkki']
    new.esittaja = esittaja
    new.nimi = nimi
    new.soinnut = soinnut
    new.linkki = linkki
    new.save()

    return redirect('/biisis')

def change_laji(request, biisi_id):
    b = get_object_or_404(Biisi, pk=biisi_id)
    aste = request.GET['aste']
    splitit = b.soinnut.split(', ')
    kaikki = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'H']
    uudetsoinnut = ""
    pituus = len(splitit)
    i = 0
    for sointu in splitit:
        i = i + 1
        if sointu.find("m") != -1:
            mollipois = sointu.replace("m", "")
            m_oli = 1
        else:
            mollipois = sointu
            m_oli = 0
        indeksi = kaikki.index(mollipois)
        kokonais = indeksi + int(aste)
        uusi = kokonais % 12
        uusisointu = kaikki[uusi]
        if m_oli == 1:
            uusisointu = uusisointu + "m"
        uudetsoinnut += uusisointu
        if i != pituus:
            uudetsoinnut += ", "
    b.soinnut = uudetsoinnut
    b.save()
    #splittaus = b.soinnut.split(', ')
    return redirect('/biisis/' + str(b.id))
    




    
    

biisis/templates/biisis/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static "biisis/bootstrap.css" %}">

<h1>{{ biisi.nimi }}</h1>

Esittaja: {{biisi.esittaja}} 

<br>
<iframe width="420" height="315" src="http://{{biisi.linkki}}" frameborder="0" ></iframe>

<br>

{% for sointu in splittaus %}
        <b>{{sointu}}</b>
{% endfor %}

<form action="{% url 'biisis:change_laji' biisi.id %}" method="get" class="form-group">
      	<input type="text" class="form-control"  name="aste" placeholder="Anna numero 1-12"/>
        <input type="submit" value="Submit" class="pure-button" style="color:white;background:rgb(20, 20, 20);"/>
</form>

biisis/templates/biisis/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static "biisis/bootstrap.css" %}">
<title> Oonalle sointukone</title>
<h1>Oonalle sointukone </h1>
<form action="{% url 'biisis:create_biisi' %}" method="get" >
        <div class="form-group" style="padding:10px;">
      	    <input type="text" class="form-control"  name="nimi" placeholder="Anna biisin nimi"/>
      	    <input type="text" class="form-control" name="esittaja" placeholder="Anna esittaja"/>
      	    <input type="text" class="form-control" name="linkki" placeholder="Anna upotettu youtubelinkki"/>
      	    <input type="text" class="form-control" name="soinnut" placeholder="Anna soinnut pilkulla eroteltuna"/>
            <input type="submit" value="Submit" class="pure-button" style="color:white;background:rgb(20, 20, 20);"/>
        </div>
</form>      

{% if biisis %}
    <ul>
    {% for biisi in biisis %}
        <li><a href="/biisis/{{ biisi.id }}/">{{ biisi.nimi }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Ei biisei</p>
{% endif %}

biisis/templates/detail.html
<h1>{{ biisi.nimi }}</h1>

{{biisi.esittaja}}

{{biisi.soinnut}}

biisis/templates/index.html
{% if biisis %}
    <ul>
    {% for biisi in biisis %}
        <li><a href="{% url 'detail' biisi.id %}">{{ biisi.esittaja }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Ei biisei</p>
{% endif %}